name: pr-checks
on:
  - pull_request

permissions:
  contents: read
  issues: read
  pull-requests: read
  checks: read

jobs:
  check_pull_request_type:
    name: Check for pull request type label
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: bug,enhancement,documentation,security
          repo_token: ${{ secrets.GITHUB_TOKEN }}
